export type Condition = { targetType?:string; forbiddenType?:string; targetShape?:string; forbiddenShape?:string; allowedTypes?:string[]; positionCondition?:'left'|'right'; distractorCondition?:'absent'|'present'; compoundCondition?:{op:'all'|'any';conditions:Condition[]} };
export type Rule = {id:string; name:string; description:string; condition:Condition; ruleSwitch?:string};
export type Level = {levelId:string; name:string; ruleId:string; stimulusCount:number; timeLimit:number; minInterval:number; maxInterval:number; stimulusDuration:number; requiredAccuracy:number; targetRatio:number; distractorRatio:number; randomPosition:boolean; countdownEnabled:boolean; enabled:boolean; secondaryRuleId?:string; switchAtTrial?:number; switchAtPercent?:number; starAccuracy?:number; starAverageMs?:number; randomizeTargets?:boolean; ruleRevision?:string; difficulty?:number; templateKey?:string; progressTemplateId?:string};
export type Stimulus = {id:string; name:string; type:string; shape:string; image:string; enabled:boolean};
export type Planned = {stimulus:Stimulus; x:number;y:number;distractor:boolean; interval:number; ruleId:string; rulePhase:number; shouldClick:boolean};
export type Trial = {trialIndex:number;stimulusId:string;stimulusType:string;stimulusShape?:string;ruleId:string;appearanceTime:number;disappearanceTime:number;positionX:number;positionY:number;shouldClick:boolean;playerClicked:boolean;clickTime:number|null;reactionTime:number|null;correct:boolean;falseAlarm:boolean;miss:boolean;previousStimulusId:string|null;rulePhase:number};
export type Stats = {average:number|null;fastest:number|null;slowest:number|null;median:number|null;stability:number|null;accuracy:number;correctClicks:number;falseAlarms:number;misses:number;passed:boolean; sampleCount:number};
export type Stars = {completed:boolean;accuracy:boolean;speed:boolean};
export type Result = {date:string;level:Level;mode:string;rule:string;stats:Stats;trials:Trial[];overridden:boolean;stars?:Stars;rules?:Rule[]};
export type Config = {settings:Record<string,any>;levels:Level[];tutorials?:(Level&{condition:Condition})[];rules:Rule[];stimuli:Stimulus[];infinite:Record<string,any>;assets:Record<string,string>;audio:any[];text:Record<string,string>};

