import {useState} from 'react';
import type {Config,Level} from '../types/index';
export type Overrides=Partial<Level>&{soundEnabled?:boolean;debug?:boolean;targetType?:string;forbiddenType?:string;mode?:string};
export function Developer({config,value,onChange,onStart}:{config:Config;value:Overrides;onChange:(v:Overrides)=>void;onStart:()=>void}){
 const [open,setOpen]=useState(false);const update=(k:string,v:any)=>onChange({...value,[k]:v});
 return <section className="developer"><button className="secondary" onClick={()=>setOpen(!open)}>Developer Settings</button>{open&&<><h2>Runtime Override</h2><p>僅影響本次工作階段，不修改 Excel。</p><div className="form-grid">{[['stimulusCount','刺激數量'],['minInterval','最短間隔 ms'],['maxInterval','最長間隔 ms'],['stimulusDuration','停留時間 ms'],['requiredAccuracy','合格比例 0–1'],['targetRatio','目標偏好比例 0–1']].map(([k,label])=><label key={k}>{label}<input type="number" step="any" value={(value as any)[k]??''} placeholder="Excel 預設" onChange={e=>update(k,e.target.value===''?undefined:Number(e.target.value))}/></label>)}<label>指定規則<select aria-label="指定規則" value={value.ruleId||''} onChange={e=>update('ruleId',e.target.value||undefined)}><option value="">關卡預設</option>{config.rules.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{['targetType','forbiddenType'].map(k=><label key={k}>{k==='targetType'?'主目標（新增 AND 條件）':'禁止目標'}<select aria-label={k} value={(value as any)[k]||''} onChange={e=>update(k,e.target.value||undefined)}><option value="">規則預設</option>{config.stimuli.filter((s,i,rows)=>rows.findIndex(r=>r.type===s.type)===i).map(s=><option key={s.type} value={s.type}>{s.type}</option>)}</select></label>)}<label>測試模式<select aria-label="測試模式" value={value.mode||'level'} onChange={e=>update('mode',e.target.value)}><option value="level">關卡模式</option><option value="infinite">無限模式</option></select></label>{[['randomPosition','隨機位置'],['countdownEnabled','倒數'],['soundEnabled','音效'],['debug','Debug 面板']].map(([k,label])=><label key={k}>{label}<select aria-label={label} value={(value as any)[k]===undefined?'':String((value as any)[k])} onChange={e=>update(k,e.target.value===''?undefined:e.target.value==='true')}><option value="">預設</option><option value="true">開啟</option><option value="false">關閉</option></select></label>)}</div><div className="actions"><button onClick={onStart}>直接開始指定測試</button><button className="secondary" onClick={()=>onChange({})}>清除覆寫</button></div></>}</section>;
}


